
  services:
    pgvector:
      image: ankane/pgvector
      container_name: pgvector-container
      restart: unless-stopped
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:5432"
      volumes:
        - ./pg_vector_data:/var/lib/postgresql/data

    n8n:
      image: n8nio/n8n:latest
      container_name: n8n
      restart: always
      ports:
        - "5678:5678"
      environment:
        N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
        N8N_HOST: 0.0.0.0
        WEBHOOK_URL: http://localhost:5678/
        N8N_LEAD_GENERATION_ENABLED: "false"
        GENERIC_TIMEZONE: Europe/Berlin

        DB_TYPE: postgresdb
        DB_POSTGRESDB_HOST: pgvector
        DB_POSTGRESDB_PORT: 5432
        DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
        DB_POSTGRESDB_USER: ${POSTGRES_USER}
        DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      depends_on:
        - pgvector
      volumes:
        - ./n8n_data:/home/node/.n8n